[tool.poetry]
name = "fastapiproject"
version = "0.1.0"
description = ""
authors = ["kooyunhyung <kooyh108@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.94.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
